### PR TITLE
Removed PolynomialMapCubedSphereDiscreteModel and PolynomialMapCubedSphereTriangulation types.

### PR DESCRIPTION
**Pull request by amartinhuertas**
They are not actually needed. We can provide the same functionality using Gridap types.

### CODE REVIEW

**Comment by davelee2804** [comment]
Hi @amartinhuertas , is this PR going to effect the use of GridapHybrid on the cubed sphere?

**Comment by amartinhuertas** [comment]
> Hi @amartinhuertas , is this PR going to effect the use of GridapHybrid on the cubed sphere?

Hi @davelee2804 ! I was revisiting the data structures for CubedSphere meshing (towards refreshing what we did) and I realized that there are two types which are just wrappers of Gridap types. Thus, we can eliminate them. This does not solve per-se the current problem we have with GridapHybrid on the cubed sphere.

**Comment by davelee2804** [comment]
Thanks for the confirmation @amartinhuertas

**Comment by amartinhuertas** [comment]
For the records, MPI tests are failing. https://github.com/gridapapps/GridapGeosciences.jl/runs/7143096336?check_suite_focus=true#step:9:102

However, I realized that exactly the same error is in the hdg_adv branch. https://github.com/gridapapps/GridapGeosciences.jl/runs/7129780507?check_suite_focus=true#step:9:102

Thus, the changes introduced in this PR seem to be inocent for this failing tests.

**Comment by amartinhuertas** [comment]
For the records, the following commit in main might circumvent (temporarily) the failing MPI Tests  https://github.com/gridapapps/GridapGeosciences.jl/commit/7cf147eac1adab2ded0022f08428ac486d8efa74

**Comment by amartinhuertas** [comment]
Ok, sequential tests pass. This seems to confirm that the two data structures I have eliminated in this PR are not actually needed.

**Comment by davelee2804** [comment]
Thanks @amartinhuertas , I'll pull that in...

**Comment by amartinhuertas** [comment]
> Thanks @amartinhuertas , I'll pull that in...

Let us see if the tests pass first in this branch. We have to pull that in the ADV-HDG branch with care. There might be conflicts. I can do it, no worries.

**Comment by davelee2804** [comment]
OK, thanks Alberto!

**Pull request merged**
